---

- name: Fail if host configuration has not been loaded
  ansible.builtin.fail:
    msg: >-
      Host configuration dictionary must be loaded
      and include epics_interface (address & broadcast),
      softioc_user, and softioc_group!
  when: >-
    host_config is not defined or
    host_config.epics_interface is not defined or
    host_config.epics_interface.address is not defined or
    host_config.epics_interface.broadcast is not defined or
    host_config.softioc_user is not defined or
    host_config.softioc_group is not defined

- name: Create top level list to track installed modules
  ansible.builtin.set_fact:
    install_module_installed: {}
    install_module_installed_list: []

- name: Install modules
  ansible.builtin.include_tasks: install-module.yml
