---

- name: Get name of substitution file
  ansible.builtin.set_fact:
    deploy_ioc_substitution_file_name: "{{ item.key }}"

- name: Get list of substitution templates if list
  ansible.builtin.set_fact:
    deploy_ioc_substitution_templates: "{{ item.value }}"
  when: item.value is not mapping

- name: Get list of substitution templates if dict
  ansible.builtin.set_fact:
    deploy_ioc_substitution_templates: "{{ item.value.templates }}"
  when: item.value is mapping and 'templates' in item.value

- name: Display substitution file name
  ansible.builtin.debug:
    msg: "{{ deploy_ioc_substitution_file_name }}"

- name: Install substitutions file
  ansible.builtin.template:
    src: templates/default.substitutions.j2
    dest: "{{ deploy_ioc_ioc_directory }}/db/{{ deploy_ioc_substitution_file_name }}.substitutions" # yamllint disable-line rule:line-length
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
