---

type: enum("admythen")
environment:
  ENGINEER: str()
  PREFIX: str()
  MYTHEN_IP: any(ip(), hostname())
  MYTHEN_IP_PORT: int(min=1, max=65535)
  XSIZE: int(min=1, default=1280)
  PORT: str()
  IP_PORT: str()

  # Optional overrides
  QSIZE: int(min=1, default=20, required=False)
  # Mythen has no Y-size, but keep for compatibility
  YSIZE: enum(1, default=1, required=False)
  NCHANS: int(min=1, default=1280, required=False)
  CBUFFS: int(min=1, default=100, required=False)
  MAX_THREADS: int(min=1, default=8, required=False)
  NELEMENTS: int(min=1, default=5000000,required=False)
