---

adpicam-01:
  type: adpicam
  environment:
    ENGINEER: C. Engineer
    PREFIX: XF:31ID1-ES{ADPICAM:01}
    XSIZE: 2048
    YSIZE: 2048

    NCHANS: 2048
    QSIZE: 2048

    # The maximum number of frames buffered in the NDPluginCircularBuff plugin
    CBUFFS: 8192
    NELEMENTS: 10000000000
