---

adgermanium_0395fac:
  name: ADGermanium
  version: 0395fac
  url: https://github.com/lijibnl/test-deployment
  include_base_ad_config: true
  module_deps:
    - adcore_60080dc
    - adsupport_6acf83f
