---

adpluginbar_448d96b:
  name: ADPluginBar
  version: 448d96b
  url: https://github.com/areaDetector/ADPluginBar
  include_base_ad_config: true
  module_deps:
    - adcore_60080dc
  pkg_deps:
    - zbar-devel
