---

pmac_f811ee1:
  name: "pmac"
  url: "https://github.com/dls-controls/pmac"
  version: "f811ee1"
  pkg_deps:
    - libssh2-devel
  # See https://github.com/DiamondLightSource/pmac/pull/131
  # on why -j flag must be avoided for now.
  compilation_command: "make"
