---
# Tasks for nsls2em role

- name: Copy base.cmd
  ansible.builtin.template:
    src: "templates/base.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Copy postInit.cmd
  ansible.builtin.template:
    src: "templates/postInit.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/postInit.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"
