---
# Tasks for ADPilatus role


- name: Copy base.cmd
  ansible.builtin.template:
    src: "templates/base.cmd.j2"
    dest: "{{ deploy_ioc_ioc_directory }}/iocBoot/base.cmd"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Copy autosave req file
  ansible.builtin.copy:
    src: "files/auto_settings.req"
    dest: "{{ deploy_ioc_as_directory }}/req/auto_settings.req"
    owner: "{{ host_config.softioc_user }}"
    group: "{{ host_config.softioc_group }}"
    mode: "0664"

- name: Create NFS mount if ramdisk path is specified
  when: ioc.ramdisk_path is defined
  block:
    - name: Create ramdisk mount directory
      ansible.builtin.file:
        path: "{{ ioc.ramdisk_path }}"
        owner: "{{ host_config.softioc_user }}"
        group: "{{ host_config.softioc_group }}"
        state: directory
        mode: "0775"

    - name: Initialize ramdisk mount on IOC server
      ansible.posix.mount:
        src: "{{ ioc.environment.PILATUS_DCU_IP }}:{{ ioc.ramdisk_path }}"
        path: "{{ ioc.ramdisk_path }}"
        fstype: nfs
        state: mounted
        opts: defaults,noac,lookupcache=none
