---

- name: Fail if host config has not been loaded if target is all
  ansible.builtin.fail:
    msg: >-
      Host configuration dictionary must be loaded
      and include epics_interface (address & broadcast),
      softioc_user, and softioc_group!
  when: >-
    manage_iocs_subcommand == "all" and
    (host_config is not defined or
    host_config.epics_interface is not defined or
    host_config.epics_interface.address is not defined or
    host_config.epics_interface.broadcast is not defined or
    host_config.softioc_user is not defined or
    host_config.softioc_group is not defined)

- name: Set manage ioc to all IOCs if requested
  ansible.builtin.set_fact:
    manage_iocs_ioc_list: >-
      "{{ host_config |
          dict2items |
          selectattr('value', 'mapping') |
          selectattr('value.type', 'defined') |
          map(attribute='key') | list }}"
  when: manage_iocs_subcommand == "all"

- name: Set manage ioc to specified IOCs if requested
  ansible.builtin.set_fact:
    manage_iocs_ioc_list: "{{ manage_iocs_subcommand.split(',') }}"
  when: manage_iocs_subcommand != "all"

- name: Show operation to be performed
  ansible.builtin.debug:
    msg: "Performing {{ manage_iocs_command }} on: {{ manage_iocs_ioc_list }}"

- name: Run tasks based on command
  ansible.builtin.include_tasks: "{{ manage_iocs_command }}.yml"
  loop: "{{ manage_iocs_ioc_list }}"
  loop_control:
    loop_var: manage_iocs_ioc_name
